### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email":"user1@email.com",
  "password":"hashed_password1"
}

###
```
