
### Get all accounts
GET http://localhost:8080/api/accounts/

###Response (HTTP/1.1 200 OK)
Content-Type: application/json
{
    "content": [
        {
            "userId": 1,
            "nickname": "bidder_bob",
            "role": [
                3
            ],
            "email": "user1@email.com",
            "phone": "123-456-7890",
            "balance": 1250.50,
            "createDate": "2024-05-24T16:23:54.19",
            "updateDate": "2024-05-24T16:23:54.19"
        },
        {
            "userId": 2,
            "nickname": "collectibles_sue",
            "role": [
                3
            ],
            "email": "seller_sue@email.com",
            "phone": "987-654-3210",
            "balance": 500.00,
            "createDate": "2024-05-24T16:23:54.19",
            "updateDate": "2024-05-24T16:23:54.19"
        },
        {
            "userId": 3,
            "nickname": "admin_ace",
            "role": [
                2
            ],
            "email": "admin_alice@email.com",
            "phone": "555-121-2555",
            "balance": 8888.88,
            "createDate": "2024-05-24T16:23:54.19",
            "updateDate": "2024-05-24T16:23:54.19"
        },
        {
            "userId": 4,
            "nickname": "arty_amanda",
            "role": [
                3
            ],
            "email": "artlover@email.com",
            "phone": "111-222-3333",
            "balance": 350.25,
            "createDate": "2024-05-24T16:23:54.19",
            "updateDate": "2024-05-24T16:23:54.19"
        },
        {
            "userId": 5,
            "nickname": "techno_tim",
            "role": [
                3
            ],
            "email": "gadget_guy@email.com",
            "phone": "444-555-6666",
            "balance": 999.99,
            "createDate": "2024-05-24T16:23:54.19",
            "updateDate": "2024-05-24T16:23:54.19"
        }
    ],
    "pageable": {
        "pageNumber": 0,
        "pageSize": 50,
        "sort": {
            "empty": false,
            "sorted": true,
            "unsorted": false
        },
        "offset": 0,
        "unpaged": false,
        "paged": true
    },
    "last": true,
    "totalElements": 5,
    "totalPages": 1,
    "size": 50,
    "number": 0,
    "sort": {
        "empty": false,
        "sorted": true,
        "unsorted": false
    },
    "first": true,
    "numberOfElements": 5,
    "empty": false
}

### Get account by id
GET http://localhost:8080/api/accounts/2

###Response (HTTP/1.1 200 OK)
Content-Type: application/json
{
    "accountId": 2,
    "nickname": "collectibles_sue",
    "role": [
        3
    ],
    "email": "seller_sue@email.com",
    "phone": "987-654-3210",
    "status": 1,
    "balance": 500.00,
    "createDate": "2024-05-24T16:23:54.19",
    "updateDate": "2024-05-24T16:23:54.19"
}



### Create account
POST http://localhost:8080/api/accounts/create
Content-Type: application/json

{
  "nickname": "",
  "role": [],
  "email": "",
  "phone": "",
  "status": 0,
  "balance": 1000.00,
  "createDate": "",
  "updateDate": ""
}

<> 2024-05-24T164331.201.json
###Response (HTTP/1.1 200 OK)
Content-Type: application/json

{
  "accountId": 6,
  "nickname": "",
  "role": [],
  "email": "",
  "phone": "",
  "status": 1,
  "balance": 1000.00,
  "createDate": "2024-05-24T16:39:25.083154",
  "updateDate": "2024-05-24T16:39:25.083154"
}

###
PUT http://localhost:8080/api/accounts/update/6
Content-Type: application/json

{
  "nickname": "phucvjp",
  "role": [1,2,3],
  "email": "p@p.p",
  "phone": "",
  "status": 1,
  "balance": 1000.00,
  "createDate": "",
  "updateDate": ""
}

<> 2024-05-24T171826.200.json
<> 2024-05-24T171506.200.json
<> 2024-05-24T171422.200.json
<> 2024-05-24T171418.200.json
<> 2024-05-24T171359.200.json
<> 2024-05-24T170633.200.json
<> 2024-05-24T170438.200.json
<> 2024-05-24T170137.200.json
<> 2024-05-24T170059.200.json
<> 2024-05-24T165638.200.json
<> 2024-05-24T165048.200.json
<> 2024-05-24T165015.200.json
<> 2024-05-24T164848.200.json
<> 2024-05-24T164654.200.json

###Response (HTTP/1.1 200 OK)
Content-Type: application/json

{
  "accountId": 6,
  "nickname": "phucvjp",
  "role": [
    1,
    3,
    2
  ],
  "email": "p@p.p",
  "phone": "",
  "status": 1,
  "balance": 1000.00,
  "createDate": null,
  "updateDate": "2024-05-24T16:42:14.153284"
}

###
DELETE http://localhost:8080/api/accounts/6
Content-Type: application/json

###Response (HTTP/1.1 200 OK)

