### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email":"admin@localhost",
  "password":"admin"
}

###Response (HTTP/1.1 200 OK)
Content-Type: application/json
{
  "id": 2,
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJzdWIiOiJhZG1pbkBsb2NhbGhvc3QiLCJpYXQiOjE3MTcwNTUxMDksImV4cCI6MTcxNzA2MDEwOX0.4n6pzcei4Fl3Vizz2esYrP7MW6MWjFq-QvuWONoKtvsYdK4PkkedxdFRETHTu3YBS8jYdpAoL-VE2boz4vym6A",
  "username": "admin",
  "roles": [
    "ADMIN"
  ],
  "refreshToken": null,
  "email": "admin@localhost",
  "phone": null,
  "nickname": null,
  "avatar": null,
  "address": null
}

### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email":"vidz752204@gmail.com",
    "password":"cute123haha",
    "confirmPassword":"cute123haha"
}

###Response (HTTP/1.1 200 OK)
Content-Type: application/json

{
  "id": 0,
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJNRU1CRVIiXSwic3ViIjoidmlkejc1MjIwNEBnbWFpbC5jb20iLCJpYXQiOjE3MTcwNTQ4MzksImV4cCI6MTcxNzA1OTgzOX0.4M8MLuOAD_W75bwRiWHTU-HYT3BaVaNhqDoa9eP6kQ4O_-1XTVFIyDntF0t7kUwei0s3I-vE0inzxBCyg6aX8g",
  "username": null,
  "roles": [
    "MEMBER"
  ],
  "refreshToken": null,
  "email": "vidz752204@gmail.com",
  "phone": null,
  "nickname": null,
  "avatar": null,
  "address": null
}


