### Get noti
GET http://localhost:8080/api/notification/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJNRU1CRVIiXSwic3ViIjoiYW5oaGRzZTE4MjMzNkBmcHQuZWR1LnZuIiwiaWF0IjoxNzE3NjY2Mjk3LCJleHAiOjE3MTc2NzEyOTcsImp0aSI6Ijg0ZjRlOGEyLWIxOTMtNGEwMC04MjlmLTYwMDEyZGUyNTRjYyJ9.GRr5lesMDaGvqdPq6CmJEHfg-oU4EmMRLEQgAO_xFf_7923FSxS1JeUIzVbZoA8mepGB5JJukg1N2m1SwUTH8Q
