/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iv4iaSKOSJQ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function AuctionSession() {
  return (
    <div
      key="1"
      className="grid min-h-screen w-full grid-cols-1 lg:grid-cols-[1fr_400px] gap-8 p-4 md:p-8 lg:p-12"
    >
      <div className="flex flex-col gap-8">
        <div className="grid gap-2">
          <h1 className="text-3xl font-bold">Auction Name</h1>
          <p className="text-gray-500 dark:text-gray-400">
            View this auction lots
          </p>
        </div>
        <div className="grid gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Auction</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <h2 className="text-xl font-semibold">Spring Art Auction</h2>
                  <p className="text-gray-500 dark:text-gray-400">
                    Join us for an exciting auction featuring a curated
                    collection of contemporary art pieces. Bidding starts on May
                    1st.
                  </p>
                </div>
                <Button size="lg">Register</Button>
              </div>
            </CardContent>
          </Card>
          <div className="grid gap-4">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-semibold">Auction Lots</h2>
              <Button variant="outline">View All</Button>
            </div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              <Card>
                <CardContent className="grid gap-4">
                  <img
                    alt="Lot 1"
                    className="rounded-lg object-cover aspect-[3/2]"
                    height="200"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="grid gap-1">
                    <h3 className="font-semibold">Lot 1: Abstract Painting</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Acrylic on canvas, 24" x 36"
                    </p>
                    <div className="font-semibold">$1,500 - $2,000</div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="grid gap-4">
                  <img
                    alt="Lot 2"
                    className="rounded-lg object-cover aspect-[3/2]"
                    height="200"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="grid gap-1">
                    <h3 className="font-semibold">Lot 2: Ceramic Vase</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Handcrafted, 8" tall
                    </p>
                    <div className="font-semibold">$500 - $800</div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="grid gap-4">
                  <img
                    alt="Lot 3"
                    className="rounded-lg object-cover aspect-[3/2]"
                    height="200"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="grid gap-1">
                    <h3 className="font-semibold">Lot 3: Vintage Typewriter</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Fully restored, 1950s model
                    </p>
                    <div className="font-semibold">$300 - $500</div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Session Details</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="grid gap-1">
              <div className="font-semibold">Auction Name</div>
              <div>Spring Art Auction</div>
            </div>
            <div className="grid gap-1">
              <div className="font-semibold">Start Date</div>
              <div>May 1, 2024</div>
            </div>
            <div className="grid gap-1">
              <div className="font-semibold">End Date</div>
              <div>May 15, 2024</div>
            </div>
            <div className="grid gap-1">
              <div className="font-semibold">Location</div>
              <div>Online</div>
            </div>
          </CardContent>
        </Card>
        <Button size="lg">Register</Button>
      </div>
    </div>
  );
}
