/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OpyqMfXPG9f
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group";
import { Button } from "@/components/ui/button";
import { UploadCloudIcon } from "lucide-react";
import axios from "axios";


export function ConsignmentRequestForm() {

  return (
    <div key="1" className="max-w-4xl mx-auto p-4 sm:p-6 md:p-8">
      <div className="space-y-4 sm:space-y-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
            List your item for consignment
          </h1>
          <p className="mt-2 text-gray-500 dark:text-gray-400">
            Fill out the form below to list your item for consignment. We'll
            review your submission and get back to you within 2 business days.
          </p>
        </div>
        <form className="space-y-4 sm:space-y-6">
          <div>
            <Label className="block font-medium" htmlFor="name">
              Contact Name
            </Label>
            <Input
              className="mt-1 block w-full"
              id="name"
              placeholder="Enter the name of your item"
              type="text"
            />
          </div>
          <div>
            <Label className="block font-medium" htmlFor="email">
              Email
            </Label>
            <Input
              className="mt-1 block w-full"
              id="email"
              placeholder="Enter your email"
              type="email"
            />
          </div>
          <div>
            <Label className="block font-medium" htmlFor="phone">
              Phone
            </Label>
            <Input
              className="mt-1 block w-full"
              id="phone"
              placeholder="Enter your phone number"
              type="tel"
            />
          </div>
          <div>
            <Label className="block font-medium" htmlFor="description">
              Description
            </Label>
            <Textarea
              className="mt-1 block w-full"
              id="description"
              placeholder="Provide a detailed description of your item"
              rows={4}
            />
          </div>
          <div>
            <Label className="block font-medium" htmlFor="images">
              Images
            </Label>
            <div className="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6 dark:border-gray-600">
              <div className="space-y-1 text-center">
                <UploadCloudIcon className="mx-auto h-12 w-12 text-gray-400" />
                <div className="flex text-sm text-gray-600 dark:text-gray-400">
                  <label
                    className="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500 dark:bg-gray-950 dark:text-indigo-500 dark:hover:text-indigo-400"
                    htmlFor="images"
                  >
                    <span>Upload a file</span>
                    <Input
                      className="sr-only"
                      id="images"
                      multiple
                      type="file"
                    />
                  </label>
                  <p className="pl-1">or drag and drop</p>
                </div>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  PNG, JPG, GIF up to 10MB
                </p>
              </div>
            </div>
          </div>
          <div>
            <Label className="block font-medium" htmlFor="communications">
              Communications Preferences
            </Label>
            <div className="mt-2 space-y-2">
              <div className="flex items-center">
                <RadioGroup name="communications" value="email">
                  <div className="flex items-center">
                    <RadioGroupItem
                      className="peer sr-only"
                      id="email"
                      value="email"
                    />
                    <Label className="flex cursor-pointer items-center rounded-md px-3 py-2 text-sm font-medium transition-colors peer-checked:bg-indigo-600 peer-checked:text-white dark:peer-checked:bg-indigo-500">
                      <div className="mr-3 h-4 w-4 rounded-full border border-gray-300 bg-white transition-colors peer-checked:border-indigo-600 peer-checked:bg-indigo-600 dark:border-gray-600 dark:bg-gray-950 dark:peer-checked:border-indigo-500 dark:peer-checked:bg-indigo-500" />
                      Email
                    </Label>
                  </div>
                  <div className="flex items-center">
                    <RadioGroupItem
                      className="peer sr-only"
                      id="phone"
                      value="phone"
                    />
                    <Label className="flex cursor-pointer items-center rounded-md px-3 py-2 text-sm font-medium transition-colors peer-checked:bg-indigo-600 peer-checked:text-white dark:peer-checked:bg-indigo-500">
                      <div className="mr-3 h-4 w-4 rounded-full border border-gray-300 bg-white transition-colors peer-checked:border-indigo-600 peer-checked:bg-indigo-600 dark:border-gray-600 dark:bg-gray-950 dark:peer-checked:border-indigo-500 dark:peer-checked:bg-indigo-500" />
                      Phone
                    </Label>
                  </div>
                  <div className="flex items-center">
                    <RadioGroupItem
                      className="peer sr-only"
                      id="text"
                      value="text"
                    />
                    <Label className="flex cursor-pointer items-center rounded-md px-3 py-2 text-sm font-medium transition-colors peer-checked:bg-indigo-600 peer-checked:text-white dark:peer-checked:bg-indigo-500">
                      <div className="mr-3 h-4 w-4 rounded-full border border-gray-300 bg-white transition-colors peer-checked:border-indigo-600 peer-checked:bg-indigo-600 dark:border-gray-600 dark:bg-gray-950 dark:peer-checked:border-indigo-500 dark:peer-checked:bg-indigo-500" />
                      Text
                    </Label>
                  </div>
                  <div className="flex items-center">
                    <RadioGroupItem
                      className="peer sr-only"
                      id="any"
                      value="any"
                    />
                    <Label className="flex cursor-pointer items-center rounded-md px-3 py-2 text-sm font-medium transition-colors peer-checked:bg-indigo-600 peer-checked:text-white dark:peer-checked:bg-indigo-500">
                      <div className="mr-3 h-4 w-4 rounded-full border border-gray-300 bg-white transition-colors peer-checked:border-indigo-600 peer-checked:bg-indigo-600 dark:border-gray-600 dark:bg-gray-950 dark:peer-checked:border-indigo-500 dark:peer-checked:bg-indigo-500" />
                      Any of the above
                    </Label>
                  </div>
                </RadioGroup>
              </div>
            </div>
          </div>
          <div className="flex justify-end">
            <Button
              className="bg-indigo-600 hover:bg-indigo-700 text-white"
              type="submit"
            >
              Submit Consignment
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
