name: Trigger auto deployment for backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - 'Backend/**'
    - '.github/workflows/backend-AutoDeployTrigger-09f2690c-6ddb-434d-9aee-526885378c7e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKEND_AZURE_SUBSCRIPTION_ID }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./backend

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Backend 
          registryUrl: biddifybackend.azurecr.io
          registryUsername: ${{ secrets.BACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKEND_REGISTRY_PASSWORD }}
          containerAppName: backend
          resourceGroup: Biddify
          imageToBuild: biddifybackend.azurecr.io/backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


