name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "12345"  # Match the password in your application.properties
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: > 
          --health-cmd="sqlcmd -U sa -P 12345 -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    
    - name: connect SQL server
      uses: 280780363/sqlserver-action@v1.0
      with:
        accept eula: Y #Required, ACCEPT_EULA confirms your acceptance of the End-User Licensing Agreement.
        sa password: 12345 # Optional, default value is SqlSever123123.
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package
      working-directory: ./Backend
