name: UNIT TEST CHECK

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup SQL Server
        uses: ankane/setup-sqlserver@v1
        with:
          accept-eula: true
          sqlserver-version: 2022
      - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE BIDDIFY'
      # - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q "ALTER LOGIN sa WITH PASSWORD = '12345678';"
      

          

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=dev
        working-directory: ./Backend
      - name: Run Tests with Maven
        run: mvn test
        working-directory: ./Backend

