name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect SQL Server
      uses: 280780363/sqlserver-action@v1.0
      with:
        accept-eula: 'Y'
        sa-password: '12345'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Wait for SQL Server to be ready
      run: |
        echo "Waiting for SQL Server to be ready..."
        for i in {1..30}; do
          if sqlcmd -S localhost -U sa -P 12345 -Q "SELECT 1" &> /dev/null; then
            echo "SQL Server is up and running"
            break
          fi
          echo "Waiting for SQL Server to be available..."
          sleep 2
        done
        sqlcmd -S localhost -U sa -P 12345 -Q "SELECT 1"

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./Backend

    - name: Run Tests with Maven
      run: mvn test
      working-directory: ./Backend
