name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: 12345
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Setup SQL Server
       uses: ankane/setup-sqlserver@v1
       with:
        accept-eula: true
        sqlserver-version: 2022
     - name: Create Biddify Database
       run: sqlcmd -S localhost -U sa -P 12345 -Q "CREATE DATABASE Biddify" # This command create the db before the next step run

   

     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
        java-version: '17'
        distribution: 'adopt'

     - name: Wait for SQL Server to be ready
       run: |
        echo "Waiting for SQL Server to be ready..."
        for i in {1..30}; do
          if sqlcmd -S localhost -U sa -P 12345 -Q "SELECT 1" &> /dev/null; then
            echo "SQL Server is up and running"
            break
          fi
          echo "Waiting for SQL Server to be available..."
          sleep 2
        done
        sqlcmd -S localhost -U sa -P 12345 -Q "SELECT 1"

     - name: Build with Maven
       run: mvn clean package
       working-directory: ./Backend

     - name: Run Tests with Maven
       run: mvn test
       working-directory: ./Backend
