name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "12345"  # Match the password in your application.properties
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >
          --health-cmd="sqlcmd -U sa -P 12345 -Q 'SELECT 1'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Wait for SQL Server to be ready
      run: |
        for i in {1..30}; do
          if sqlcmd -S localhost -U sa -P 12345 -Q "SELECT 1" &> /dev/null; then
            echo "SQL Server is up and running"
            break
          fi
          echo "Waiting for SQL Server to be available..."
          sleep 2
        done

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./Backend
